import type { Metadata } from 'next';
import '../styles/globals.css';
import { circular } from '../styles/fonts';

export const metadata: Metadata = {
  title: 'Darkroom Finder',
  description: 'Generated by create next app',
  keywords: 'analog, darkroom, film, laboratory, lab, enlarger'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-dark-200 text-gray-dark-1200 text-lg ${circular.className}`}>
        {children}
      </body>
    </html>
  );
}
